import { useState } from "react";
import { CheckCircle2, FileCheck2, MoreHorizontal, Plus, Search } from "lucide-react";
import { Badge, Button, Page, PageHeader, Panel, TextField } from "../../design-system/react";
import { categories, products } from "../data/menu";
import { mxn } from "../domain/money";

export function CatalogPage() {
  const [query, setQuery] = useState(""); const [available, setAvailable] = useState<Record<string, boolean>>(() => Object.fromEntries(products.map((product) => [product.id, product.available]))); const filtered = products.filter((product) => product.name.toLowerCase().includes(query.toLowerCase()));
  return <Page size="wide"><PageHeader eyebrow="MENÚ Y DISPONIBILIDAD" title="Catálogo" description="Menú precargado desde “menú abril 2026.pdf”. Revisa antes de publicarlo." action={<Button variant="primary"><Plus size={18} /> Nuevo producto</Button>} /><Panel className="mb-5 flex flex-col gap-4 border-tertiary/30 bg-tertiary-fixed/25 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><FileCheck2 className="mt-0.5 shrink-0 text-tertiary" /><div><p className="font-bold">Validación gerencial pendiente</p><p className="mt-1 text-sm text-on-surface-variant">{products.length} productos · {categories.length} categorías · precios finales MXN</p></div></div><Button variant="success"><CheckCircle2 size={18} /> Validar y publicar</Button></Panel><Panel className="overflow-hidden"><div className="border-b border-outline-variant/30 p-4"><div className="relative max-w-sm"><Search size={18} className="absolute left-3 top-[15px] text-outline" /><TextField className="mt-0 pl-10" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar en el catálogo" /></div></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-surface-container-low text-xs uppercase text-on-surface-variant"><tr><th className="px-5 py-4">Producto</th><th className="px-5 py-4">Categoría</th><th className="px-5 py-4">Precio base</th><th className="px-5 py-4">Horario</th><th className="px-5 py-4">Disponible</th><th /></tr></thead><tbody className="divide-y divide-outline-variant/25">{filtered.map((product) => <tr key={product.id}><td className="px-5 py-4"><p className="font-semibold">{product.name}</p><p className="max-w-sm truncate text-xs text-on-surface-variant">{product.description || (product.variants ? `${product.variants.length} variantes` : "Precio único")}</p></td><td className="px-5 py-4"><Badge>{categories.find((category) => category.id === product.categoryId)?.name}</Badge></td><td className="px-5 py-4 font-bold">{mxn.format(product.price)}</td><td className="px-5 py-4 text-on-surface-variant">{product.schedule || "Todo el día"}</td><td className="px-5 py-4"><button role="switch" aria-checked={available[product.id]} onClick={() => setAvailable((state) => ({ ...state, [product.id]: !state[product.id] }))} className={`relative h-7 w-12 rounded-full transition ${available[product.id] ? "bg-tertiary" : "bg-outline-variant"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition-all ${available[product.id] ? "left-6" : "left-1"}`} /></button></td><td className="px-4"><Button size="icon" variant="ghost"><MoreHorizontal size={18} /></Button></td></tr>)}</tbody></table></div></Panel></Page>;
}
