import { Eye, Filter, Search } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import { Button, Page, PageHeader, Panel, SelectField, TextField } from "../../design-system/react";
import { mxn, orderTotal } from "../domain/money";
import { OrderStatusBadge, SyncStatusBadge } from "../components/StatusBadge";
import { useApp } from "../state/AppContext";

export function OrdersPage() {
  const { orders } = useApp(); const [status, setStatus] = useState("all"); const [search, setSearch] = useState("");
  const filtered = orders.filter((order) => (status === "all" || order.status === status) && `${order.folio} ${order.customerName ?? ""} ${order.tableId ?? ""}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
  return <Page size="wide"><PageHeader eyebrow="HISTORIAL OPERATIVO" title="Pedidos" description="Abiertos, terminados, cancelados y revertidos sin eliminar el registro original." /><Panel className="mb-4 flex flex-col gap-3 p-4 sm:flex-row"><div className="relative flex-1"><Search size={18} className="absolute left-3 top-[15px] text-outline" /><TextField className="mt-0 pl-10" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Folio, mesa o nombre" /></div><div className="flex items-center gap-2"><Filter size={18} className="text-outline" /><SelectField className="mt-0 min-w-44" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">Todos los estados</option><option value="open">Abiertos</option><option value="preparing">En preparación</option><option value="ready">Listos</option><option value="closed">Cobrados</option><option value="cancelled">Cancelados</option><option value="reversed">Revertidos</option></SelectField></div></Panel><Panel className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-surface-container-low text-xs uppercase tracking-wider text-on-surface-variant"><tr><th className="px-5 py-4">Pedido</th><th className="px-5 py-4">Destino</th><th className="px-5 py-4">Estado</th><th className="px-5 py-4">Sincronización</th><th className="px-5 py-4 text-right">Total</th><th className="px-5 py-4" /></tr></thead><tbody className="divide-y divide-outline-variant/25">{filtered.map((order) => <tr key={order.id} className="hover:bg-surface-container-low/60"><td className="px-5 py-4"><p className="font-bold">#{order.folio}</p><p className="text-xs text-on-surface-variant">{new Date(order.openedAt).toLocaleString("es-MX", { dateStyle: "short", timeStyle: "short" })}</p></td><td className="px-5 py-4 font-semibold">{order.type === "table" ? `Mesa ${order.tableId?.replace("t", "")}` : order.customerName || "Para llevar"}</td><td className="px-5 py-4"><OrderStatusBadge status={order.status} /></td><td className="px-5 py-4"><SyncStatusBadge status={order.syncStatus} /></td><td className="px-5 py-4 text-right font-bold">{mxn.format(orderTotal(order))}</td><td className="px-5 py-4"><Link to={`/venta/${order.id}`}><Button size="icon" variant="ghost" aria-label="Ver orden"><Eye size={18} /></Button></Link></td></tr>)}</tbody></table></div></Panel></Page>;
}
