import { CheckCircle2, ChefHat, Clock3, Coffee, ShoppingBag } from "lucide-react";
import { Badge, Button, EmptyState, Page, PageHeader, Panel } from "../../design-system/react";
import { deliverableItemCount } from "../domain/order";
import { useApp } from "../state/AppContext";

export function PreparationPage() {
  const { orders, markOrderReady } = useApp();
  const queue = orders.filter((order) => order.status === "preparing").sort((a, b) => a.openedAt.localeCompare(b.openedAt));
  const ready = orders.filter((order) => order.status === "ready");
  return <Page size="wide"><PageHeader eyebrow="COLA COMPARTIDA" title="Preparación" description="Comandas activas visibles para todo el equipo." action={<Badge tone="primary">{queue.length} en cola</Badge>} />
    {!queue.length && !ready.length ? <Panel><EmptyState icon={<ChefHat />} title="La barra está al día" description="Las nuevas comandas aparecerán aquí en cuanto se envíen." /></Panel> : <div className="grid gap-6 xl:grid-cols-[1fr_330px]"><section><h2 className="mb-3 text-sm font-bold uppercase tracking-wider text-on-surface-variant">Por preparar</h2><div className="grid gap-4 md:grid-cols-2">{queue.map((order, index) => <Panel key={order.id} className="overflow-hidden"><div className="flex items-center justify-between border-b border-outline-variant/30 bg-primary-fixed/40 px-5 py-4"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-on-primary">{order.type === "table" ? <Coffee size={19} /> : <ShoppingBag size={19} />}</span><div><p className="font-bold">{order.type === "table" ? `Mesa ${order.tableId?.replace("t", "")}` : order.customerName || "Para llevar"}</p><p className="text-xs text-on-surface-variant">Orden #{order.folio}</p></div></div><Badge tone={index === 0 ? "danger" : "neutral"}><Clock3 size={12} /> {Math.max(1, Math.round((Date.now() - new Date(order.openedAt).getTime()) / 60000))} min</Badge></div><div className="space-y-3 p-5">{order.items.filter((item) => item.status === "dispatched").map((item) => <div key={item.id} className="flex gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-surface-container-high text-sm font-bold">{item.quantity}</span><div><p className="font-semibold">{item.name}</p>{item.variant && <p className="text-xs text-on-surface-variant">{item.variant}</p>}{item.modifiers.map((modifier) => <p key={modifier.id} className="text-xs text-on-surface-variant">+ {modifier.name}</p>)}{item.notes && <p className="text-xs font-semibold text-primary">Nota: {item.notes}</p>}</div></div>)}<Button variant="success" className="mt-2 w-full" onClick={() => void markOrderReady(order.id)}><CheckCircle2 size={18} /> Marcar todo listo</Button></div></Panel>)}</div></section><aside><h2 className="mb-3 text-sm font-bold uppercase tracking-wider text-on-surface-variant">Listos para entregar</h2><div className="space-y-3">{ready.map((order) => <Panel key={order.id} className="border-tertiary/30 bg-tertiary-fixed/30 p-4"><div className="flex items-center justify-between"><div><p className="font-bold">{order.type === "table" ? `Mesa ${order.tableId?.replace("t", "")}` : order.customerName || "Para llevar"}</p><p className="text-xs text-on-surface-variant">#{order.folio} · {deliverableItemCount(order.items)} {deliverableItemCount(order.items) === 1 ? "artículo" : "artículos"}</p></div><CheckCircle2 className="text-tertiary" /></div></Panel>)}{!ready.length && <p className="rounded-xl border border-dashed border-outline-variant p-5 text-center text-sm text-on-surface-variant">Aún no hay pedidos listos.</p>}</div></aside></div>}
  </Page>;
}
